apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: tg-go-clearance
  namespace: test-a
  labels:
    app: tg-go-clearance
spec:
  targetReference:
    name: svc-go-clearance
  defaultConfiguration:
    targetGroupName: tg-go-clearance
    targetType: ip
  routeConfigurations:
    - routeIdentifier:
        kind: HTTPRoute
        name: go-clearance-route
        namespace: test-a
      targetGroupProps:
        healthCheckConfig:
          healthCheckProtocol: HTTP
          healthCheckPath: /health
          healthCheckPort: traffic-port 
          healthyThresholdCount: 2 
          unhealthyThresholdCount: 2