apiVersion: v1
kind: Service
metadata:
  name: &app-name svc-go-clearance
  namespace: test-a
  labels:
    app: *app-name
spec:
  type: ClusterIP
  ports:
  - port: 7003
    targetPort: 7003
    protocol: TCP
    name: http
  selector:
    app: go-clearance
